// Simulated data generator for a government-facing dashboard
export function generateGovernmentSnapshot() {
  const now = new Date()
  const powerKw = Number((20 + Math.random() * 30).toFixed(1)) // solar power generated by canopies
  const shading = Number((55 + Math.random() * 35).toFixed(0)) // % of paths currently shaded
  const carbonOffset = Number((0.5 + Math.random() * 1.5).toFixed(2)) // tons CO2 saved today
  const uptime = Number((95 + Math.random() * 5).toFixed(2)) // % asset uptime
  const incidents = Math.random() < 0.1 ? 1 + Math.floor(Math.random() * 3) : 0
  const maintenanceDue = Math.random() < 0.2
  const complianceScore = Number((80 + Math.random() * 20).toFixed(0))

  // simple timeseries for energy today (hourly)
  const hours = Array.from({ length: 10 }, (_, i) => `${(8 + i).toString().padStart(2, '0')}:00`)
  const energySeries = hours.map((t, i) => ({ t, kw: Math.max(0, 10 + Math.sin(i / 2) * 12 + Math.random() * 4) }))

  const assets = [
    { id: 'CAN-001', name: 'Rizal Circle Canopy', status: 'operational', lastService: daysAgo(22), district: 'Ermita' },
    { id: 'CAN-014', name: 'Luneta South Axis', status: maintenanceDue ? 'maintenance-due' : 'operational', lastService: daysAgo(92), district: 'Malate' },
    { id: 'AQ-102', name: 'AQ Node – Museum Gate', status: 'operational', lastService: daysAgo(34), district: 'Ermita' },
    { id: 'CAM-025', name: 'Footfall Cam – Baywalk', status: incidents ? 'attention' : 'operational', lastService: daysAgo(15), district: 'Baywalk' }
  ]

  return { now, powerKw, shading, carbonOffset, uptime, incidents, maintenanceDue, complianceScore, energySeries, assets }
}

function daysAgo(n) {
  const d = new Date()
  d.setDate(d.getDate() - n)
  return d
}
