// Simulated data generator for a government-facing dashboard
export function generateGovernmentSnapshot({ location } = {}) {
  const now = new Date()
  
  // Location-specific variations
  const locationFactor = getLocationFactor(location?.id)
  const basePower = 20 + locationFactor.power * 15
  
  const powerKw = Number((basePower + Math.random() * 30).toFixed(1)) // solar power generated by canopies
  const networkUptime = Number((96 + Math.random() * 4).toFixed(1)) // % of sensors online and transmitting
  const carbonOffset = Number((0.5 + Math.random() * 1.5).toFixed(2)) // tons CO2 saved today
  const uptime = Number((95 + Math.random() * 5).toFixed(2)) // % asset uptime
  const incidents = Math.random() < 0.1 ? 1 + Math.floor(Math.random() * 3) : 0
  const maintenanceDue = Math.random() < 0.2
  const complianceScore = Number((80 + Math.random() * 20).toFixed(0))

  // simple timeseries for energy today (hourly)
  const hours = Array.from({ length: 10 }, (_, i) => `${(8 + i).toString().padStart(2, '0')}:00`)
  const energySeries = hours.map((t, i) => ({ 
    t, 
    kw: Math.max(0, (basePower * 0.5) + Math.sin(i / 2) * 12 + Math.random() * 4) 
  }))

  // Location-specific asset names
  const assets = generateLocationAssets(location, maintenanceDue, incidents)

  return { now, powerKw, networkUptime, carbonOffset, uptime, incidents, maintenanceDue, complianceScore, energySeries, assets }
}

function getLocationFactor(locationId) {
  const factors = {
    luneta: { power: 1.0, canopyCount: 1.0 }, // Baseline
    binondo: { power: 0.8, canopyCount: 0.7 }, // Smaller area, dense
    intramuros: { power: 1.2, canopyCount: 1.1 }, // Large heritage site
    pasigriver: { power: 0.9, canopyCount: 0.8 } // Linear park
  }
  return factors[locationId] || factors.luneta
}

function generateLocationAssets(location, maintenanceDue, incidents) {
  if (!location) {
    // Default Luneta assets
    return [
      { id: 'CAN-001', name: 'Rizal Circle Canopy', status: 'operational', lastService: daysAgo(22), district: 'Ermita' },
      { id: 'CAN-014', name: 'Luneta South Axis', status: maintenanceDue ? 'maintenance-due' : 'operational', lastService: daysAgo(92), district: 'Malate' },
      { id: 'AQ-102', name: 'AQ Node – Museum Gate', status: 'operational', lastService: daysAgo(34), district: 'Ermita' },
      { id: 'CAM-025', name: 'Footfall Cam – Baywalk', status: incidents ? 'attention' : 'operational', lastService: daysAgo(15), district: 'Baywalk' }
    ]
  }

  const assetTemplates = {
    luneta: [
      { id: 'LUN-001', name: 'Rizal Circle Canopy', landmark: 'Rizal Monument' },
      { id: 'LUN-014', name: 'South Axis Shade', landmark: 'Museum Cluster' },
      { id: 'LUN-102', name: 'AQ Node - Museum Gate', landmark: 'National Museum' },
      { id: 'LUN-025', name: 'Footfall Cam - Baywalk', landmark: 'Manila Bay' }
    ],
    binondo: [
      { id: 'BIN-001', name: 'Ongpin Street Canopy', landmark: 'Ongpin Commercial' },
      { id: 'BIN-008', name: 'Church Plaza Shade', landmark: 'Binondo Church' },
      { id: 'BIN-102', name: 'AQ Node - Market', landmark: 'Wet Market' },
      { id: 'BIN-019', name: 'Footfall Cam - Escolta', landmark: 'Escolta Street' }
    ],
    intramuros: [
      { id: 'INT-001', name: 'Fort Santiago Canopy', landmark: 'Fort Santiago' },
      { id: 'INT-012', name: 'Plaza Roma Shade', landmark: 'Manila Cathedral' },
      { id: 'INT-103', name: 'AQ Node - San Agustin', landmark: 'San Agustin Church' },
      { id: 'INT-027', name: 'Footfall Cam - Walls', landmark: 'City Walls' }
    ],
    pasigriver: [
      { id: 'PAS-001', name: 'Ferry Terminal Canopy', landmark: 'Escolta Pier' },
      { id: 'PAS-009', name: 'Esplanade Shade', landmark: 'Riverwalk' },
      { id: 'PAS-104', name: 'AQ Node - Waterfront', landmark: 'River Edge' },
      { id: 'PAS-021', name: 'Footfall Cam - Bridge', landmark: 'Jones Bridge' }
    ]
  }

  const templates = assetTemplates[location.id] || assetTemplates.luneta
  
  return templates.map((template, idx) => ({
    id: template.id,
    name: template.name,
    status: idx === 1 && maintenanceDue ? 'maintenance-due' : idx === 3 && incidents ? 'attention' : 'operational',
    lastService: daysAgo(Math.floor(Math.random() * 90) + 10),
    district: location.district,
    landmark: template.landmark
  }))
}

function daysAgo(n) {
  const d = new Date()
  d.setDate(d.getDate() - n)
  return d
}
